package utility;

/**
 * Created by zhangbaoshan on 2016/5/23.
 */
public enum TestPurpose {
    FULL_FILL,PARTIAL_FILL_THEN_CANCEL,CANCEL_REJECTED,CANCEL_THEN_PARTIAL_FILL,
    CANCEL_DIRECTLY_FROM_EXG,DO_NOTHING,PEGGING_CANCEL,MANUALLY_ORDER_CANCEL_THEN_PARTIAL_FILL,
    CANCEL_REJECT_THEN_FILL_DIRECTLY_FROM_EXG
}
