import com.csc108.drools.OrderMessage;
import com.csc108.log.LogFactory;
import quickfix.fix42.NewOrderSingle;

no-loop true
enabled true
salience 2

rule "NewOrderRule"
    when
        task:OrderMessage(task.getMessage()!=null && IsNewOrderMessage())
    then
        LogFactory.droolsLog("Before calling NewOrderRule : "+task.getMessage());
        if(task.getMessage().isSetField(10)){
                task.getMessage().removeField(10);
            }

            if(task.getMessage().isSetField(6076)){
                task.getMessage().removeField(6076);
            }

          	if(task.getMessage().isSetField(6297)){
          	    task.getMessage().removeField(6297);
            }

          	if(task.getMessage().isSetField(6298)){
          	    task.getMessage().removeField(6298);
            }          	

          	if(task.getMessage().isSetField(6065)){
          	    task.getMessage().removeField(6065);
            }

          	if(task.getMessage().isSetField(111)){
          	        task.getMessage().removeField(111);
            }

          	if(task.getMessage().isSetField(115)){
          	    task.getMessage().removeField(115);
            }

            if(task.getMessage().isSetField(116)){
          	    task.getMessage().removeField(116);
            }

            if(task.getMessage().isSetField(126)){
                task.getMessage().removeField(126);
            }

            if(task.getMessage().isSetField(58)){
                task.getMessage().removeField(58);
            }

            if(task.getMessage().isSetField(59)){
                task.getMessage().removeField(59);
            }

            if(task.getMessage().isSetField(50)){
                task.getMessage().removeField(50);
            }

            if(task.getMessage().isSetField(207)){
           	    task.getMessage().setString(100,task.getMessage().getString(207));
            }

            if(!task.getMessage().isSetField(21)){
                task.getMessage().setString(21,"1");
            }

            if(!task.getMessage().isSetField(109)){
                task.getMessage().setString(109,"Cld_RootNet_01");
            }
			
			if(!task.getMessage().isSetField(6064)){
          	    task.getMessage().setString(6064,"30");
            }
			
			if(task.getMessage().isSetField(526)){
				String tag526 =task.getMessage().getString(526);
				task.getMessage().setString(1,tag526.substring(0,tag526.indexOf('_')));
			}
			
        LogFactory.droolsLog("After calling NewOrderRule : "+task.getMessage());
end
